steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke
      terraform init
    fi 
# [STOP tf-init]      

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke
      terraform plan -var-file="variables.tfvars" -lock=false
    fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke     
      terraform apply -var-file="variables
      tfvars" -auto-approve -lock=false
    fi
  timeout: 3600s
# [END tf-apply]


# [CREATE Namespaces]
- id : 'create namespace'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    if [ $BRANCH_NAME = wahid ]; then
      gcloud container clusters get-credentials infra-test --region us-west1 --project test-project-ws-342013
      namespaceStatus=$(kubectl get ns $BRANCH_NAME -o json | jq .status.phase -r)
      if [ $namespaceStatus == "Active" ]
      then
        echo "namespace is present"
      else
        kubectl create namespace $BRANCH_NAME
    fi
timeout: 3600s
