steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
    echo "***********************"
    echo "The Commit was made in the branch: "
    echo "$BRANCH_NAME"
    echo "***********************"
# Terraform initialize
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      echo "The dir is changed"
      terraform init
    fi
# Terraform Plan
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      terraform plan -var-file="../../env/dev.tfvars"
    fi
# Terraform Apply
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      terraform apply -var-file="../../env/dev.tfvars" -auto-approve -lock=false
    fi
  timeout: 1800s

# Namespace creation
- id: 'Namespace creation'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=namespace.yaml
  - --location=${_LOCATION}
  - --cluster=${_CLUSTER}

# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'