steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
# [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke
      terraform init
    fi 
# [STOP tf-init]      

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke
      terraform plan -var-file="variables.tfvars" -lock=false
    fi 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    if [ -d "profiles/gke/" ]; then
      cd profiles/gke     
      terraform apply -var-file="variables.tfvars" -auto-approve -lock=false
    fi
  timeout: 3600s
# [END tf-apply]


# [CREATE Namespaces]
- id : 'create namespace'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'bash'
  args: ['./bash.sh', '$BRANCH_NAME']
  timeout: 3600s
timeout: 3600s
