steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
    echo "***********************"
    echo "Welcome, Can I have the password please?"
    echo "$$password"
    echo "***********************"
  secretEnv: ['password']
  availableSecrets:
    secretManager:
    - versionName: projects/${_PROJECT}/secrets/password/versions/1
      env: 'password'
# Start
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
    echo "***********************"
    echo "The Commit was made in the branch: "
    echo "$BRANCH_NAME"
    echo "***********************"
# Terraform initialize
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      echo "The dir is changed"
      terraform init
    fi
# Terraform Plan
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      terraform plan -var-file="../../env/dev.tfvars"
    fi
# Terraform Apply
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
    if [ $BRANCH_NAME = black ]; then
      cd profiles/infra
      echo "Here we will apply something"
    fi
#      terraform apply -var-file="../../env/dev.tfvars" -auto-approve
# Namespace creation
- id: 'Namespace creation'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - '-c'
  - |
    echo "Here we will apply something"
#  - run
#  - --filename=namespace.yaml
#  - --location=${_LOCATION}
#  - --cluster=${_CLUSTER}

# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: ''E2_HIGHCPU_32'