  # Entrypoint, timeout and environment variables
steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
      echo "***********************"
      echo "The Commit was made in the branch: "
      echo "$BRANCH_NAME"
      echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd INFRASTRUCTURE/profiles/cloud-run
      terraform init
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd INFRASTRUCTURE/profiles/cloud-run
      terraform plan -var-file="./../../environments/production.tfvars"
  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd INFRASTRUCTURE/profiles/cloud-run
      terraform apply -var-file="gs://green-project-backend/resources/development.tfvars" -var="container_image=gcr.io/${PROJECT_ID}/mycalc" -auto-approve