apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata: 
  name: test-1
---
apiVersion: v1
kind: Namespace
metadata: 
  name: test-2
---
apiVersion: v1
kind: Namespace
metadata: 
  name: test-3
