region= "europe-north1"
project_1= "team-2-a"
project_2= "team-2-b"
cluster_name="gke-boutique-cluster"
zone= "europe-north1-a"
#machine_type= "e2-medium"
#vm_name= "nutcracker-vm"
#boot_disk_image= "debian-cloud/debian-9"
peer_name_1= "gke-peer"
peer_name_2= "redis-peer"

